// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist1
arma::mat dist1(arma::mat coords);
RcppExport SEXP _spbrom_dist1(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(dist1(coords));
    return rcpp_result_gen;
END_RCPP
}
// dist2
arma::mat dist2(arma::mat coords);
RcppExport SEXP _spbrom_dist2(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(dist2(coords));
    return rcpp_result_gen;
END_RCPP
}
// MuSigmaUpdate
Rcpp::List MuSigmaUpdate(arma::vec x, arma::vec mu, arma::mat Sigma, int n);
RcppExport SEXP _spbrom_MuSigmaUpdate(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(MuSigmaUpdate(x, mu, Sigma, n));
    return rcpp_result_gen;
END_RCPP
}
// MuSigma
Rcpp::List MuSigma(arma::mat x);
RcppExport SEXP _spbrom_MuSigma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(MuSigma(x));
    return rcpp_result_gen;
END_RCPP
}
// MuSigmaUpdate2
Rcpp::List MuSigmaUpdate2(arma::vec x_new, arma::vec x_old, arma::vec mu_old, arma::mat Sigma_old, int fn_new, int fn_old, int n_new, int d);
RcppExport SEXP _spbrom_MuSigmaUpdate2(SEXP x_newSEXP, SEXP x_oldSEXP, SEXP mu_oldSEXP, SEXP Sigma_oldSEXP, SEXP fn_newSEXP, SEXP fn_oldSEXP, SEXP n_newSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_old(x_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_old(mu_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_old(Sigma_oldSEXP);
    Rcpp::traits::input_parameter< int >::type fn_new(fn_newSEXP);
    Rcpp::traits::input_parameter< int >::type fn_old(fn_oldSEXP);
    Rcpp::traits::input_parameter< int >::type n_new(n_newSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(MuSigmaUpdate2(x_new, x_old, mu_old, Sigma_old, fn_new, fn_old, n_new, d));
    return rcpp_result_gen;
END_RCPP
}
// MuSigmaUpdate3
Rcpp::List MuSigmaUpdate3(arma::vec x_new, arma::vec x_old, arma::vec mu_old, arma::mat Sigma_old, int fn_new, int fn_old, int n_new, int d);
RcppExport SEXP _spbrom_MuSigmaUpdate3(SEXP x_newSEXP, SEXP x_oldSEXP, SEXP mu_oldSEXP, SEXP Sigma_oldSEXP, SEXP fn_newSEXP, SEXP fn_oldSEXP, SEXP n_newSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_old(x_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_old(mu_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_old(Sigma_oldSEXP);
    Rcpp::traits::input_parameter< int >::type fn_new(fn_newSEXP);
    Rcpp::traits::input_parameter< int >::type fn_old(fn_oldSEXP);
    Rcpp::traits::input_parameter< int >::type n_new(n_newSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(MuSigmaUpdate3(x_new, x_old, mu_old, Sigma_old, fn_new, fn_old, n_new, d));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm
arma::vec rtnorm(const int N, arma::vec mu);
RcppExport SEXP _spbrom_rtnorm(SEXP NSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(N, mu));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm_numeric
double rtnorm_numeric(double mu, double sigma);
RcppExport SEXP _spbrom_rtnorm_numeric(SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm_numeric(mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm1
double rtnorm1(double mu, double sigma, double a, double b);
RcppExport SEXP _spbrom_rtnorm1(SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm1(mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// dtnorm1
double dtnorm1(double x, double mu, double sigma, double a, double b);
RcppExport SEXP _spbrom_dtnorm1(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dtnorm1(x, mu, sigma, a, b));
    return rcpp_result_gen;
END_RCPP
}
// dnorm1
double dnorm1(double x, double mu, double prec);
RcppExport SEXP _spbrom_dnorm1(SEXP xSEXP, SEXP muSEXP, SEXP precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type prec(precSEXP);
    rcpp_result_gen = Rcpp::wrap(dnorm1(x, mu, prec));
    return rcpp_result_gen;
END_RCPP
}
// dA
double dA(arma::vec la, arma::vec a, arma::vec mu, arma::mat Sigma_inv, arma::vec mu_likelihood, arma::mat Sigma_inv_likelihood);
RcppExport SEXP _spbrom_dA(SEXP laSEXP, SEXP aSEXP, SEXP muSEXP, SEXP Sigma_invSEXP, SEXP mu_likelihoodSEXP, SEXP Sigma_inv_likelihoodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type la(laSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_inv(Sigma_invSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_likelihood(mu_likelihoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_inv_likelihood(Sigma_inv_likelihoodSEXP);
    rcpp_result_gen = Rcpp::wrap(dA(la, a, mu, Sigma_inv, mu_likelihood, Sigma_inv_likelihood));
    return rcpp_result_gen;
END_RCPP
}
// uglm
arma::mat uglm(const int N, const int k, const arma::vec Nweak, arma::mat X, const arma::mat X0, const arma::mat X1, arma::vec beta, arma::vec Wtls, double a11, arma::vec decay, const int M, const arma::cube dist, const int decayPrior, const int n, const int T, const int L, const arma::uvec site, const arma::uvec year, const arma::uvec day, const arma::uvec weak, const arma::uvec Weak, const arma::vec noNA, const arma::uvec indLag, const arma::vec prob, arma::vec abLim, const arma::uvec weakl0, const arma::vec probl0, const arma::mat V, const double na, const double nb, const double diag_b, const arma::vec da, const arma::vec db, arma::mat keep, const int nSims, const int nThin, const int nBurnin, const int nReport);
RcppExport SEXP _spbrom_uglm(SEXP NSEXP, SEXP kSEXP, SEXP NweakSEXP, SEXP XSEXP, SEXP X0SEXP, SEXP X1SEXP, SEXP betaSEXP, SEXP WtlsSEXP, SEXP a11SEXP, SEXP decaySEXP, SEXP MSEXP, SEXP distSEXP, SEXP decayPriorSEXP, SEXP nSEXP, SEXP TSEXP, SEXP LSEXP, SEXP siteSEXP, SEXP yearSEXP, SEXP daySEXP, SEXP weakSEXP, SEXP WeakSEXP, SEXP noNASEXP, SEXP indLagSEXP, SEXP probSEXP, SEXP abLimSEXP, SEXP weakl0SEXP, SEXP probl0SEXP, SEXP VSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP diag_bSEXP, SEXP daSEXP, SEXP dbSEXP, SEXP keepSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Nweak(NweakSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Wtls(WtlsSEXP);
    Rcpp::traits::input_parameter< double >::type a11(a11SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< const int >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const int >::type decayPrior(decayPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type T(TSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type site(siteSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type year(yearSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type day(daySEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak(weakSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type Weak(WeakSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type noNA(noNASEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag(indLagSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob(probSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type abLim(abLimSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weakl0(weakl0SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type probl0(probl0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const double >::type na(naSEXP);
    Rcpp::traits::input_parameter< const double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< const double >::type diag_b(diag_bSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type db(dbSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(uglm(N, k, Nweak, X, X0, X1, beta, Wtls, a11, decay, M, dist, decayPrior, n, T, L, site, year, day, weak, Weak, noNA, indLag, prob, abLim, weakl0, probl0, V, na, nb, diag_b, da, db, keep, nSims, nThin, nBurnin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// bglm
arma::mat bglm(const int N, const int k, const arma::vec Nweak, arma::mat X, const arma::mat X0, const arma::mat X1, arma::mat beta, arma::mat Wtls, double a11, double a22, double a21, arma::vec decay, const int M, const arma::cube dist, const int decayPrior, const int n, const int T, const int L, const arma::uvec site, const arma::uvec year, const arma::uvec day, const arma::uvec weak1, const arma::uvec weak2, const arma::uvec Weak1, const arma::uvec Weak2, const arma::vec noNA1, const arma::vec noNA2, const arma::uvec indLag1, const arma::uvec indLag2, const arma::mat prob, arma::mat abLim, const arma::uvec weak1l0, const arma::uvec weak2l0, const arma::vec prob1l0, const arma::vec prob2l0, const arma::mat V, const double na, const double nb, const double diag_b, const arma::vec da, const arma::vec db, arma::mat keep, const int nSims, const int nThin, const int nBurnin, const int nReport);
RcppExport SEXP _spbrom_bglm(SEXP NSEXP, SEXP kSEXP, SEXP NweakSEXP, SEXP XSEXP, SEXP X0SEXP, SEXP X1SEXP, SEXP betaSEXP, SEXP WtlsSEXP, SEXP a11SEXP, SEXP a22SEXP, SEXP a21SEXP, SEXP decaySEXP, SEXP MSEXP, SEXP distSEXP, SEXP decayPriorSEXP, SEXP nSEXP, SEXP TSEXP, SEXP LSEXP, SEXP siteSEXP, SEXP yearSEXP, SEXP daySEXP, SEXP weak1SEXP, SEXP weak2SEXP, SEXP Weak1SEXP, SEXP Weak2SEXP, SEXP noNA1SEXP, SEXP noNA2SEXP, SEXP indLag1SEXP, SEXP indLag2SEXP, SEXP probSEXP, SEXP abLimSEXP, SEXP weak1l0SEXP, SEXP weak2l0SEXP, SEXP prob1l0SEXP, SEXP prob2l0SEXP, SEXP VSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP diag_bSEXP, SEXP daSEXP, SEXP dbSEXP, SEXP keepSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Nweak(NweakSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wtls(WtlsSEXP);
    Rcpp::traits::input_parameter< double >::type a11(a11SEXP);
    Rcpp::traits::input_parameter< double >::type a22(a22SEXP);
    Rcpp::traits::input_parameter< double >::type a21(a21SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< const int >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const int >::type decayPrior(decayPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type T(TSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type site(siteSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type year(yearSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type day(daySEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak1(weak1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak2(weak2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type Weak1(Weak1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type Weak2(Weak2SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type noNA1(noNA1SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type noNA2(noNA2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag1(indLag1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag2(indLag2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type prob(probSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type abLim(abLimSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak1l0(weak1l0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak2l0(weak2l0SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob1l0(prob1l0SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob2l0(prob2l0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const double >::type na(naSEXP);
    Rcpp::traits::input_parameter< const double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< const double >::type diag_b(diag_bSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type db(dbSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(bglm(N, k, Nweak, X, X0, X1, beta, Wtls, a11, a22, a21, decay, M, dist, decayPrior, n, T, L, site, year, day, weak1, weak2, Weak1, Weak2, noNA1, noNA2, indLag1, indLag2, prob, abLim, weak1l0, weak2l0, prob1l0, prob2l0, V, na, nb, diag_b, da, db, keep, nSims, nThin, nBurnin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// bglm2
arma::mat bglm2(const int N, const int k, const arma::vec Nweak, arma::mat X, const arma::mat X0, const arma::mat X1, arma::mat beta, arma::mat Wtls, arma::vec a11, arma::vec a22, arma::vec a21, arma::vec hpA, const arma::mat onen, const int q, arma::vec decay, const int M, const arma::cube dist, const int decayPrior, const int n, const int T, const int L, const arma::uvec site, const arma::uvec year, const arma::uvec day, const arma::uvec weak1, const arma::uvec weak2, const arma::uvec Weak1, const arma::uvec Weak2, const arma::vec noNA1, const arma::vec noNA2, const arma::uvec indLag1, const arma::uvec indLag2, const arma::mat prob, arma::mat abLim, const arma::uvec weak1l0, const arma::uvec weak2l0, const arma::vec prob1l0, const arma::vec prob2l0, const arma::mat Vk, const arma::mat Vq, const double na, const double nb, const double ga, const double gb, const arma::vec da, const arma::vec db, arma::mat keep, const int nSims, const int nThin, const int nBurnin, const int nReport);
RcppExport SEXP _spbrom_bglm2(SEXP NSEXP, SEXP kSEXP, SEXP NweakSEXP, SEXP XSEXP, SEXP X0SEXP, SEXP X1SEXP, SEXP betaSEXP, SEXP WtlsSEXP, SEXP a11SEXP, SEXP a22SEXP, SEXP a21SEXP, SEXP hpASEXP, SEXP onenSEXP, SEXP qSEXP, SEXP decaySEXP, SEXP MSEXP, SEXP distSEXP, SEXP decayPriorSEXP, SEXP nSEXP, SEXP TSEXP, SEXP LSEXP, SEXP siteSEXP, SEXP yearSEXP, SEXP daySEXP, SEXP weak1SEXP, SEXP weak2SEXP, SEXP Weak1SEXP, SEXP Weak2SEXP, SEXP noNA1SEXP, SEXP noNA2SEXP, SEXP indLag1SEXP, SEXP indLag2SEXP, SEXP probSEXP, SEXP abLimSEXP, SEXP weak1l0SEXP, SEXP weak2l0SEXP, SEXP prob1l0SEXP, SEXP prob2l0SEXP, SEXP VkSEXP, SEXP VqSEXP, SEXP naSEXP, SEXP nbSEXP, SEXP gaSEXP, SEXP gbSEXP, SEXP daSEXP, SEXP dbSEXP, SEXP keepSEXP, SEXP nSimsSEXP, SEXP nThinSEXP, SEXP nBurninSEXP, SEXP nReportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Nweak(NweakSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wtls(WtlsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a11(a11SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a22(a22SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a21(a21SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type hpA(hpASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type onen(onenSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< const int >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::cube >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const int >::type decayPrior(decayPriorSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type T(TSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type site(siteSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type year(yearSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type day(daySEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak1(weak1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak2(weak2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type Weak1(Weak1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type Weak2(Weak2SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type noNA1(noNA1SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type noNA2(noNA2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag1(indLag1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag2(indLag2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type prob(probSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type abLim(abLimSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak1l0(weak1l0SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak2l0(weak2l0SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob1l0(prob1l0SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob2l0(prob2l0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Vk(VkSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Vq(VqSEXP);
    Rcpp::traits::input_parameter< const double >::type na(naSEXP);
    Rcpp::traits::input_parameter< const double >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< const double >::type ga(gaSEXP);
    Rcpp::traits::input_parameter< const double >::type gb(gbSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type da(daSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type db(dbSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< const int >::type nSims(nSimsSEXP);
    Rcpp::traits::input_parameter< const int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< const int >::type nBurnin(nBurninSEXP);
    Rcpp::traits::input_parameter< const int >::type nReport(nReportSEXP);
    rcpp_result_gen = Rcpp::wrap(bglm2(N, k, Nweak, X, X0, X1, beta, Wtls, a11, a22, a21, hpA, onen, q, decay, M, dist, decayPrior, n, T, L, site, year, day, weak1, weak2, Weak1, Weak2, noNA1, noNA2, indLag1, indLag2, prob, abLim, weak1l0, weak2l0, prob1l0, prob2l0, Vk, Vq, na, nb, ga, gb, da, db, keep, nSims, nThin, nBurnin, nReport));
    return rcpp_result_gen;
END_RCPP
}
// predGlmBerKFCV
arma::cube predGlmBerKFCV(const int B, const arma::vec Nweak, const int newN, arma::mat X, const arma::mat X0, const arma::mat X1, const arma::mat beta1, const arma::mat beta2, const arma::uvec weak1, const arma::uvec weak2, const arma::uvec indLag1, const arma::uvec indLag2, const arma::vec prob1, const arma::vec prob2);
RcppExport SEXP _spbrom_predGlmBerKFCV(SEXP BSEXP, SEXP NweakSEXP, SEXP newNSEXP, SEXP XSEXP, SEXP X0SEXP, SEXP X1SEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP weak1SEXP, SEXP weak2SEXP, SEXP indLag1SEXP, SEXP indLag2SEXP, SEXP prob1SEXP, SEXP prob2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Nweak(NweakSEXP);
    Rcpp::traits::input_parameter< const int >::type newN(newNSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak1(weak1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak2(weak2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag1(indLag1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag2(indLag2SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob1(prob1SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob2(prob2SEXP);
    rcpp_result_gen = Rcpp::wrap(predGlmBerKFCV(B, Nweak, newN, X, X0, X1, beta1, beta2, weak1, weak2, indLag1, indLag2, prob1, prob2));
    return rcpp_result_gen;
END_RCPP
}
// predictBglm
arma::cube predictBglm(const int B, const arma::vec Nweak, const int newN, const int n, const int newn, const int T, const int L, arma::mat X, const arma::mat X0, const arma::mat X1, arma::vec year, arma::vec day, arma::uvec newsite, arma::vec newyear, arma::vec newday, arma::cube dist, const arma::mat beta1, const arma::mat beta2, const arma::mat W1tls, const arma::mat W2tls, const arma::mat a, bool spA, arma::mat hpA, const arma::mat onen, const arma::mat onenew, const int q, const arma::mat decay, const int M, const arma::uvec weak1, const arma::uvec weak2, const arma::uvec indLag1, const arma::uvec indLag2, const arma::vec prob1, const arma::vec prob2);
RcppExport SEXP _spbrom_predictBglm(SEXP BSEXP, SEXP NweakSEXP, SEXP newNSEXP, SEXP nSEXP, SEXP newnSEXP, SEXP TSEXP, SEXP LSEXP, SEXP XSEXP, SEXP X0SEXP, SEXP X1SEXP, SEXP yearSEXP, SEXP daySEXP, SEXP newsiteSEXP, SEXP newyearSEXP, SEXP newdaySEXP, SEXP distSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP W1tlsSEXP, SEXP W2tlsSEXP, SEXP aSEXP, SEXP spASEXP, SEXP hpASEXP, SEXP onenSEXP, SEXP onenewSEXP, SEXP qSEXP, SEXP decaySEXP, SEXP MSEXP, SEXP weak1SEXP, SEXP weak2SEXP, SEXP indLag1SEXP, SEXP indLag2SEXP, SEXP prob1SEXP, SEXP prob2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type Nweak(NweakSEXP);
    Rcpp::traits::input_parameter< const int >::type newN(newNSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type newn(newnSEXP);
    Rcpp::traits::input_parameter< const int >::type T(TSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type year(yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type day(daySEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type newsite(newsiteSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type newyear(newyearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type newday(newdaySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type dist(distSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type W1tls(W1tlsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type W2tls(W2tlsSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< bool >::type spA(spASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hpA(hpASEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type onen(onenSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type onenew(onenewSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< const int >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak1(weak1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type weak2(weak2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag1(indLag1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type indLag2(indLag2SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob1(prob1SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type prob2(prob2SEXP);
    rcpp_result_gen = Rcpp::wrap(predictBglm(B, Nweak, newN, n, newn, T, L, X, X0, X1, year, day, newsite, newyear, newday, dist, beta1, beta2, W1tls, W2tls, a, spA, hpA, onen, onenew, q, decay, M, weak1, weak2, indLag1, indLag2, prob1, prob2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spbrom_dist1", (DL_FUNC) &_spbrom_dist1, 1},
    {"_spbrom_dist2", (DL_FUNC) &_spbrom_dist2, 1},
    {"_spbrom_MuSigmaUpdate", (DL_FUNC) &_spbrom_MuSigmaUpdate, 4},
    {"_spbrom_MuSigma", (DL_FUNC) &_spbrom_MuSigma, 1},
    {"_spbrom_MuSigmaUpdate2", (DL_FUNC) &_spbrom_MuSigmaUpdate2, 8},
    {"_spbrom_MuSigmaUpdate3", (DL_FUNC) &_spbrom_MuSigmaUpdate3, 8},
    {"_spbrom_rtnorm", (DL_FUNC) &_spbrom_rtnorm, 2},
    {"_spbrom_rtnorm_numeric", (DL_FUNC) &_spbrom_rtnorm_numeric, 2},
    {"_spbrom_rtnorm1", (DL_FUNC) &_spbrom_rtnorm1, 4},
    {"_spbrom_dtnorm1", (DL_FUNC) &_spbrom_dtnorm1, 5},
    {"_spbrom_dnorm1", (DL_FUNC) &_spbrom_dnorm1, 3},
    {"_spbrom_dA", (DL_FUNC) &_spbrom_dA, 6},
    {"_spbrom_uglm", (DL_FUNC) &_spbrom_uglm, 38},
    {"_spbrom_bglm", (DL_FUNC) &_spbrom_bglm, 46},
    {"_spbrom_bglm2", (DL_FUNC) &_spbrom_bglm2, 51},
    {"_spbrom_predGlmBerKFCV", (DL_FUNC) &_spbrom_predGlmBerKFCV, 14},
    {"_spbrom_predictBglm", (DL_FUNC) &_spbrom_predictBglm, 34},
    {NULL, NULL, 0}
};

RcppExport void R_init_spbrom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
