# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist1 <- function(coords) {
    .Call('_spbrom_dist1', PACKAGE = 'spbrom', coords)
}

dist2 <- function(coords) {
    .Call('_spbrom_dist2', PACKAGE = 'spbrom', coords)
}

MuSigmaUpdate <- function(x, mu, Sigma, n) {
    .Call('_spbrom_MuSigmaUpdate', PACKAGE = 'spbrom', x, mu, Sigma, n)
}

MuSigma <- function(x) {
    .Call('_spbrom_MuSigma', PACKAGE = 'spbrom', x)
}

MuSigmaUpdate2 <- function(x_new, x_old, mu_old, Sigma_old, fn_new, fn_old, n_new, d) {
    .Call('_spbrom_MuSigmaUpdate2', PACKAGE = 'spbrom', x_new, x_old, mu_old, Sigma_old, fn_new, fn_old, n_new, d)
}

MuSigmaUpdate3 <- function(x_new, x_old, mu_old, Sigma_old, fn_new, fn_old, n_new, d) {
    .Call('_spbrom_MuSigmaUpdate3', PACKAGE = 'spbrom', x_new, x_old, mu_old, Sigma_old, fn_new, fn_old, n_new, d)
}

rtnorm <- function(N, mu) {
    .Call('_spbrom_rtnorm', PACKAGE = 'spbrom', N, mu)
}

rtnorm_numeric <- function(mu, sigma) {
    .Call('_spbrom_rtnorm_numeric', PACKAGE = 'spbrom', mu, sigma)
}

rtnorm1 <- function(mu, sigma, a, b) {
    .Call('_spbrom_rtnorm1', PACKAGE = 'spbrom', mu, sigma, a, b)
}

dtnorm1 <- function(x, mu, sigma, a, b) {
    .Call('_spbrom_dtnorm1', PACKAGE = 'spbrom', x, mu, sigma, a, b)
}

dnorm1 <- function(x, mu, prec) {
    .Call('_spbrom_dnorm1', PACKAGE = 'spbrom', x, mu, prec)
}

dA <- function(la, a, mu, Sigma_inv, mu_likelihood, Sigma_inv_likelihood) {
    .Call('_spbrom_dA', PACKAGE = 'spbrom', la, a, mu, Sigma_inv, mu_likelihood, Sigma_inv_likelihood)
}

uglm <- function(N, k, Nweak, X, X0, X1, beta, Wtls, a11, decay, M, dist, decayPrior, n, T, L, site, year, day, weak, Weak, noNA, indLag, prob, abLim, weakl0, probl0, V, na, nb, diag_b, da, db, keep, nSims, nThin, nBurnin, nReport) {
    .Call('_spbrom_uglm', PACKAGE = 'spbrom', N, k, Nweak, X, X0, X1, beta, Wtls, a11, decay, M, dist, decayPrior, n, T, L, site, year, day, weak, Weak, noNA, indLag, prob, abLim, weakl0, probl0, V, na, nb, diag_b, da, db, keep, nSims, nThin, nBurnin, nReport)
}

bglm <- function(N, k, Nweak, X, X0, X1, beta, Wtls, a11, a22, a21, decay, M, dist, decayPrior, n, T, L, site, year, day, weak1, weak2, Weak1, Weak2, noNA1, noNA2, indLag1, indLag2, prob, abLim, weak1l0, weak2l0, prob1l0, prob2l0, V, na, nb, diag_b, da, db, keep, nSims, nThin, nBurnin, nReport) {
    .Call('_spbrom_bglm', PACKAGE = 'spbrom', N, k, Nweak, X, X0, X1, beta, Wtls, a11, a22, a21, decay, M, dist, decayPrior, n, T, L, site, year, day, weak1, weak2, Weak1, Weak2, noNA1, noNA2, indLag1, indLag2, prob, abLim, weak1l0, weak2l0, prob1l0, prob2l0, V, na, nb, diag_b, da, db, keep, nSims, nThin, nBurnin, nReport)
}

bglm2 <- function(N, k, Nweak, X, X0, X1, beta, Wtls, a11, a22, a21, hpA, onen, q, decay, M, dist, decayPrior, n, T, L, site, year, day, weak1, weak2, Weak1, Weak2, noNA1, noNA2, indLag1, indLag2, prob, abLim, weak1l0, weak2l0, prob1l0, prob2l0, Vk, Vq, na, nb, ga, gb, da, db, keep, nSims, nThin, nBurnin, nReport) {
    .Call('_spbrom_bglm2', PACKAGE = 'spbrom', N, k, Nweak, X, X0, X1, beta, Wtls, a11, a22, a21, hpA, onen, q, decay, M, dist, decayPrior, n, T, L, site, year, day, weak1, weak2, Weak1, Weak2, noNA1, noNA2, indLag1, indLag2, prob, abLim, weak1l0, weak2l0, prob1l0, prob2l0, Vk, Vq, na, nb, ga, gb, da, db, keep, nSims, nThin, nBurnin, nReport)
}

predGlmBerKFCV <- function(B, Nweak, newN, X, X0, X1, beta1, beta2, weak1, weak2, indLag1, indLag2, prob1, prob2) {
    .Call('_spbrom_predGlmBerKFCV', PACKAGE = 'spbrom', B, Nweak, newN, X, X0, X1, beta1, beta2, weak1, weak2, indLag1, indLag2, prob1, prob2)
}

predictBglm <- function(B, Nweak, newN, n, newn, T, L, X, X0, X1, year, day, newsite, newyear, newday, dist, beta1, beta2, W1tls, W2tls, a, spA, hpA, onen, onenew, q, decay, M, weak1, weak2, indLag1, indLag2, prob1, prob2) {
    .Call('_spbrom_predictBglm', PACKAGE = 'spbrom', B, Nweak, newN, n, newn, T, L, X, X0, X1, year, day, newsite, newyear, newday, dist, beta1, beta2, W1tls, W2tls, a, spA, hpA, onen, onenew, q, decay, M, weak1, weak2, indLag1, indLag2, prob1, prob2)
}

